version: '2'

volumes: 
  database_data:
    driver: local


services:
  nginx:
    build: ./docker/nginx/
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: ./docker/php/
    expose: 
      - 9000
    volumes:
      - /var/www:/var/www/html
  mysql:
    image: mysql:latest
    expose:
      - 3306
    volumes: 
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupaltest
      MYSQL_USER: root
      MYSQL_PASSWORD: root 
