FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install software-properties-common -y
RUN apt-add-repository ppa:ondrej/php
RUN apt-get update
RUN apt-get install  php7.0-fpm php7.0-mysql php7.0 php7.0-gd -y